// Webpack config — single file, switches behaviour based on `mode`.
// CommonJS because the project package.json declares "type": "module" but
// webpack's standard config-loading expects CJS unless we use a .mjs name +
// async config, which buys us nothing here.

const path = require("node:path");
const fs = require("node:fs");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyPlugin = require("copy-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const TerserPlugin = require("terser-webpack-plugin");

// Read the extension version from package.json so it can be stamped onto every
// telemetry signal without hardcoding.
const pkgVersion = (() => {
  try {
    return require("./package.json").version || "0.0.0";
  } catch {
    return "0.0.0";
  }
})();

/**
 * Build-time telemetry config injected via DefinePlugin as the global
 * `__EMR_TELEMETRY_CONFIG__`. The key is vendor-neutral by design — it carries
 * whatever the active sink needs (e.g. a 1DS instrumentation key).
 *
 *   TELEMETRY_KEY       optional ingestion/instrumentation key. Telemetry stays
 *                       disabled unless a build explicitly supplies one.
 *   TELEMETRY_ENDPOINT  optional collector endpoint override
 *   TELEMETRY_DEBUG     "1" to force the console sink (local diagnostics)
 *
 * `environment` is derived from the webpack mode so prod and dev builds can be
 * sliced apart in the telemetry backend.
 */
function telemetryDefineConfig(isDev) {
  const key = process.env.TELEMETRY_KEY || "";
  return {
    key,
    endpoint: process.env.TELEMETRY_ENDPOINT || "",
    appVersion: pkgVersion,
    environment: isDev ? "development" : "production",
    enabled: Boolean(key),
    debug: process.env.TELEMETRY_DEBUG === "1",
  };
}

/** @type {(env: any, argv: { mode?: string }) => import('webpack').Configuration} */
module.exports = (env, argv) => {
  const isDev = argv.mode !== "production";
  // ADO requires the PR-tab iframe to be served over HTTPS (mixed-content
  // blocking). Standalone dev preview is loaded directly in the browser and
  // works fine over HTTP. Default to HTTP so the integrated browser doesn't
  // hit `ERR_CERT_AUTHORITY_INVALID` on the self-signed cert. Opt into HTTPS
  // by passing `--env https` (used by `npm run dev:https`).
  // "Verification" dev mode: run the app locally under a production-representative
  // security posture instead of the fast HMR loop. The published extension ships
  // NO CSP of its own — the ADO host wraps the iframe in its own restrictive CSP,
  // `sandbox`, and X-Frame-Options (see docs/threat-model.md). Those host controls
  // only exist in production, so a regression that relies on inline <script> or
  // eval() would pass every local dev run and only break once loaded inside ADO.
  //
  // Strict mode closes that gap: it serves a self-CSP that forbids inline scripts
  // and eval (mirroring the host) so such a regression fails immediately in the
  // local HTTPS server. It is opt-in (`--env strict`, used by `npm run dev:verify`)
  // because the everyday loop needs HMR's inline runtime + eval source maps, which
  // a strict CSP necessarily blocks. Strict implies HTTPS since it targets the
  // real in-ADO iframe scenario.
  const useStrict = env?.strict === true || process.env.EMR_DEV_STRICT === "1";
  const useHttps =
    useStrict || env?.https === true || process.env.EMR_DEV_HTTPS === "1";
  const devProtocol = useHttps ? "https" : "http";
  const devOrigin = `${devProtocol}://localhost:3000`;

  // When running HTTPS, load the locally-trusted cert generated by
  // `scripts/setup-dev-cert.ps1` (npm run setup:cert) if available. Falls
  // back to webpack-dev-server's auto cert with a warning if not.
  let httpsServerOptions = undefined;
  if (useHttps) {
    const pfxPath = path.resolve(__dirname, "certs/localhost.pfx");
    const pfxPwPath = path.resolve(__dirname, "certs/localhost.pfx.password");
    if (fs.existsSync(pfxPath) && fs.existsSync(pfxPwPath)) {
      httpsServerOptions = {
        pfx: fs.readFileSync(pfxPath),
        passphrase: fs.readFileSync(pfxPwPath, "utf8"),
      };
    } else {
      // eslint-disable-next-line no-console
      console.warn(
        "[webpack] HTTPS requested but certs/localhost.pfx not found. " +
          "Run `npm run setup:cert` once to generate a locally-trusted cert. " +
          "Falling back to webpack-dev-server's untrusted auto cert.",
      );
    }
  }

  /** @type {import('webpack').Configuration} */
  const config = {
    mode: isDev ? "development" : "production",
    entry: {
      "pr-tab/pr-tab": "./src/pr-tab/pr-tab.tsx",
      // Full-page "Documents" hub (top-level Documents hub group): the
      // full-width reading + browsing surface the menu action navigates to.
      "hub/documents-hub": "./src/hub/markdownReviewHub.tsx",
    },
    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "[name].js",
      clean: true,
      // In dev we point at the localhost devOrigin so the iframe in real
      // ADO can pull assets from the dev server. In prod we use "auto",
      // which lets HtmlWebpackPlugin emit script URLs relative to the
      // generated HTML (otherwise an empty publicPath duplicates the
      // subfolder — e.g. dist/pr-tab/pr-tab/pr-tab.js).
      publicPath: isDev ? `${devOrigin}/` : "auto",
    },
    // Strict verification mode forbids eval() via CSP, so it cannot use the
    // eval-based dev source map; fall back to a real source-map file there.
    devtool: isDev
      ? useStrict
        ? "source-map"
        : "eval-cheap-module-source-map"
      : "source-map",
    resolve: {
      extensions: [".ts", ".tsx", ".js", ".jsx"],
      // Aliases:
      //   1. azure-devops-ui — its .scss imports need this alias to resolve.
      //   2. azure-devops-extension-sdk — CRITICAL. The published v4 package
      //      ships dual entries in `exports`: "./esm/SDK.min.js" for ESM
      //      imports (our app code) and "./SDK.min.js" for CommonJS/AMD
      //      requires (used internally by azure-devops-extension-api's
      //      compiled AMD `define([...])` calls). Without this alias webpack
      //      bundles BOTH files, producing two independent SDK instances
      //      with separate XDMChannelManager + parentChannel + pending-call
      //      maps. The result is that `getClient(...).<anyMethod>()` posts
      //      messages on instance B's channel but instance A's handler
      //      sees the response first, logs "No handler found", and instance
      //      B's promise never resolves. Pinning every import of the SDK
      //      to a single file restores a single shared SDK instance and
      //      the REST clients work correctly.
      alias: {
        "azure-devops-ui": path.resolve(
          __dirname,
          "node_modules/azure-devops-ui",
        ),
        "azure-devops-extension-sdk$": path.resolve(
          __dirname,
          "node_modules/azure-devops-extension-sdk/SDK.js",
        ),
      },
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: "ts-loader",
            options: {
              transpileOnly: isDev,
              compilerOptions: {
                noUnusedLocals: !isDev,
                noUnusedParameters: !isDev,
              },
            },
          },
        },
        {
          // `import css from "…/foo.css?raw"` returns the file's contents as
          // a string instead of injecting a <style> tag. Used by
          // src/theme/markdownStyles.ts so we can swap GitHub markdown
          // light/dark variants at runtime when the host theme changes.
          //
          // NOTE: declared as a sibling of the SCSS-pipeline rule (not
          // inside `oneOf`) because in practice webpack 5 was running the
          // sass-loader chain on `?raw` resources even with the `oneOf`
          // arm in place. Two top-level rules with mutually-exclusive
          // `resourceQuery` conditions match unambiguously.
          test: /\.css$/,
          resourceQuery: /raw/,
          type: "asset/source",
        },
        {
          test: /\.s?css$/,
          resourceQuery: { not: [/raw/] },
          use: [
            // Dev: inject <style> tags so HMR can hot-swap styles. Prod:
            // extract to a separate, cacheable, minifiable .css asset so the
            // CSS is not carried as (poorly compressible) JS string literals
            // inside the entry bundles.
            isDev ? "style-loader" : MiniCssExtractPlugin.loader,
            { loader: "css-loader", options: { url: false } },
            { loader: "sass-loader", options: { api: "modern" } },
          ],
        },
        {
          test: /\.(png|svg|woff2?|ttf|eot)$/,
          type: "asset/resource",
        },
      ],
    },
    plugins: [
      new webpack.DefinePlugin({
        // Vendor-neutral telemetry config; absent values resolve to a no-op
        // sink at runtime. Stringified so the object literal is inlined.
        __EMR_TELEMETRY_CONFIG__: JSON.stringify(telemetryDefineConfig(isDev)),
      }),
      new HtmlWebpackPlugin({
        template: "./src/pr-tab/pr-tab.html",
        filename: "pr-tab/pr-tab.html",
        chunks: ["pr-tab/pr-tab"],
        inject: "body",
      }),
      new HtmlWebpackPlugin({
        template: "./src/hub/markdownReviewHub.html",
        filename: "hub/documents-hub.html",
        chunks: ["hub/documents-hub"],
        inject: "body",
      }),
      new CopyPlugin({
        patterns: [{ from: "static", to: "../static", noErrorOnMissing: true }],
      }),
      // Prod only: emit component CSS as standalone [name].css assets so it is
      // minified by CssMinimizerPlugin and served/cached separately from JS.
      ...(isDev ? [] : [new MiniCssExtractPlugin({ filename: "[name].css" })]),
    ],
    devServer: isDev
      ? {
          server: httpsServerOptions
            ? { type: "https", options: httpsServerOptions }
            : devProtocol,
          port: 3000,
          host: "localhost",
          // HMR relies on an inline runtime + eval; strict mode's CSP blocks
          // both, so it serves a static, production-representative bundle.
          hot: !useStrict,
          liveReload: !useStrict,
          static: { directory: path.resolve(__dirname, "dist") },
          // ADO loads the iframe cross-origin, so we need permissive CORS in dev.
          // Access-Control-Allow-Private-Network answers Chromium's Private Network
          // Access preflight: a public site (dev.azure.com) embedding a localhost
          // iframe is blocked (ERR_ABORTED) unless the local server opts in here.
          headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Private-Network": "true",
            // Baseline hardening that is always safe to assert locally.
            "X-Content-Type-Options": "nosniff",
            // In verification mode, wrap the app in a self-CSP that mirrors the
            // restrictions ADO's host CSP imposes in production: no inline
            // <script>, no eval(), no plugins, locked base URI, and framing
            // limited to the ADO origins that embed the extension. This makes
            // an accidental inline-script/eval regression fail here instead of
            // only inside the real host. Kept out of the normal loop because it
            // is incompatible with HMR.
            ...(useStrict
              ? {
                  "Content-Security-Policy": [
                    "default-src 'self'",
                    "script-src 'self'",
                    // Component styles are injected as <style> tags by
                    // style-loader in dev, which requires 'unsafe-inline' for
                    // styles only (never scripts).
                    "style-src 'self' 'unsafe-inline'",
                    // `blob:` is required for user/author avatars: the host
                    // avatar resolver fetches the image with auth and hands the
                    // app a `URL.createObjectURL(blob)` src (see
                    // resolveAdoAvatarObjectUrl). Without it, strict mode blocks
                    // every photo and Avatar silently falls back to initials.
                    "img-src 'self' data: blob: https:",
                    "font-src 'self' data:",
                    "connect-src 'self' https:",
                    "object-src 'none'",
                    "base-uri 'none'",
                    "frame-ancestors https://dev.azure.com https://*.visualstudio.com",
                  ].join("; "),
                }
              : {}),
          },
          allowedHosts: "all",
          client: { overlay: { errors: true, warnings: false } },
          devMiddleware: { writeToDisk: false },
        }
      : undefined,
    performance: isDev
      ? { hints: false }
      : {
          // Warn (do not fail the build) when an entry's total initial
          // download crosses these budgets; the hard gate lives in
          // scripts/check-bundle-size.mjs (npm run size).
          hints: "warning",
          maxEntrypointSize: 900 * 1024,
          maxAssetSize: 900 * 1024,
        },
    optimization: {
      // Explicit in prod so the minifier settings below are used instead of
      // webpack's defaults; disabled in dev for fast rebuilds + readable output.
      minimize: !isDev,
      minimizer: [
        new TerserPlugin({
          // Move license banners to a single .LICENSE.txt sidecar instead of
          // leaving them inline in the shipped JS.
          extractComments: /@preserve|@license|@cc_on/i,
          terserOptions: {
            compress: {
              // Strip dev-only noise from prod bundles. Only `console.log` is
              // dropped — that's the step-logging in PrTabApp/DocumentsHubApp
              // whose args are side-effect-free. `console.info`/`console.debug`
              // are intentionally KEPT: the telemetry console sink
              // (src/telemetry/sinks/consoleSink.ts, active with
              // TELEMETRY_DEBUG=1) emits diagnostics through them, and
              // console.warn/error carry real runtime diagnostics.
              drop_debugger: true,
              pure_funcs: ["console.log"],
            },
            format: { comments: false },
          },
        }),
        new CssMinimizerPlugin(),
      ],
    },
    stats: { errorDetails: true },
  };

  return config;
};
